Update sphinx.yaml

diff --git a/.github/workflows/sphinx.yaml b/.github/workflows/sphinx.yaml
--- a/.github/workflows/sphinx.yaml
+++ b/.github/workflows/sphinx.yaml
@@ -1,6 +1,5 @@
 name: Build-sphinx-docs
 
-# Controls when the workflow will run
 on:
   push:
     branches: [master]
@@ -24,13 +23,21 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          pip install ghp-import  # Install ghp-import tool
+          pip install ghp-import
 
       - name: Build HTML
         run: |
           cd docs/
           make html
 
+      - name: List files in docs/_build
+        run: ls -R docs/_build
+
       - name: Deploy to GitHub Pages
         run: |
-          ghp-import -n -p -f docs/_build/html
+          if [ -d "docs/_build/html" ]; then
+            ghp-import -n -p -f docs/_build/html
+          else
+            echo "Error: docs/_build/html directory not found. Skipping deployment."
+            exit 1
+          fi
